---
version: "3"
services:
    proxy:
        build: ./pyproxy
        env_file:
          - ./erasure.env
        ports:
          - 3000:8000
        deploy:
            mode: replicated
            placement:
                constraints: [node.role == manager]
        depends_on:
          - storage-node-1
          - storage-node-2
          - storage-node-3
          - storage-node-4
          - storage-node-5
          - storage-node-6
          - storage-node-7
          - storage-node-8
          - storage-node-9
          - storage-node-10
          - storage-node-11
          - storage-node-12
          - storage-node-13
          - storage-node-14
          - storage-node-15
          - storage-node-16
    zoo1:
        image: zookeeper
        restart: always
        ports:
          - 2181:2181
        environment:
          - ZOO_MY_ID=1
        deploy:
            mode: replicated
            placement:
                constraints: [node.role == manager]

    metadata:
        image: redis:3.2.8
        command: redis-server --appendonly yes
        deploy:
            mode: replicated
            placement:
                constraints: [node.role == manager]
        volumes:
          - ./volumes/metadata/:/data/
    storage-node-1:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-1:/data/
        container_name: storage-node-1
    storage-node-2:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-2:/data/
        container_name: storage-node-2
    storage-node-3:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-3:/data/
        container_name: storage-node-3
    storage-node-4:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-4:/data/
        container_name: storage-node-4
    storage-node-5:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-5:/data/
        container_name: storage-node-5
    storage-node-6:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-6:/data/
        container_name: storage-node-6
    storage-node-7:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-7:/data/
        container_name: storage-node-7
    storage-node-8:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-8:/data/
        container_name: storage-node-8
    storage-node-9:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-9:/data/
        container_name: storage-node-9
    storage-node-10:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-10:/data/
        container_name: storage-node-10
    storage-node-11:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-11:/data/
        container_name: storage-node-11
    storage-node-12:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-12:/data/
        container_name: storage-node-12
    storage-node-13:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-13:/data/
        container_name: storage-node-13
    storage-node-14:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-14:/data/
        container_name: storage-node-14
    storage-node-15:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-15:/data/
        container_name: storage-node-15
    storage-node-16:
        environment:
          - MINIO_ACCESS_KEY=playcloud
          - MINIO_SECRET_KEY=playcloud
        image: minio/minio:latest
        command: server /data
        volumes:
          - ./volumes/storage-node-16:/data/
        container_name: storage-node-16
